# Configuration

_python_reference_version: &python_reference_version PYTHON="3.8.1"

_python_reference_environment: &python_reference_environment
  env: *python_reference_version

_repo_filter: &repo_filter
  repo: Placu95/Experiment-2020-FutureInternet-LoRa

# System

language: minimal
git:
  depth: false
os:
  - osx
  - windows
  - linux

addons:
  apt:
    packages:
    - ghostscript
    - dvipng
    - texlive-latex-base
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-extra-utils

env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - JDK="adopt@1.11"
    - JDK="adopt@1.14"

# Base configuration

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - chmod +x gradlew
install:
  - source $GRAVIS/install-jdk
script:
  - travis_retry ./gradlew clean smallBatch
before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.pyenv
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Stages

stages:
  - name: charts
    # Always run if it's a cron job
    # Always run if there is no tag
    # Also run for tags if the commit message is custom (it's not a data generation commit)
    if: type = cron OR tag is blank AND NOT commit_message =~ /\[\s*(AUTOMATIC|DATA|DEPLOY).*\].*/
  - name: deploy
    # Run always, unless it's a deployment created by auto-tag (the task has already been successfully completed)
    # or is the bot to update gradle wrapper
    if: tag is blank OR NOT tag =~ /.*-\d{4}-\d{2}-\d{2}T\d*/ AND NOT commit_message =~ /\s*Upgrade Gradle Wrapper to.*/
  - name: test
    if: tag is blank

# Operations

_make_charts: &make_charts
  os: linux
  language: minimal
  stage: charts
  install:
    - source $GRAVIS/install-python
    - travis_retry pip install --upgrade pip --user
    - travis_retry pip install -r requirements.txt --user
  script:
    - travis_wait 50 python process.py
    - travis_wait 10 python processRoundByPl.py
    - find charts -name "*.pdf" -exec pdfcrop --clip {} {} \;

_deploy_base: &deploy_base
  provider: releases
  edge: true
  file:
    - "${TRAVIS_BUILD_DIR}/*.tar.gz"

_deploy: &deploy
  before_deploy:
    # The script requires appropriate git configuration.
    # This README's got my name so it's quicker for me to copy/paste. You want to change it.
    - tar -czvf "charts.tar.gz" -C $TRAVIS_BUILD_DIR/charts/ .
    - git config --local user.name "Placu"
    - git config --local user.email "andrea.placuzzi@studio.unibo.it"
    - $GRAVIS/autotag
  deploy:
    - <<: *deploy_base
      on:
        <<: *repo_filter
        tags: true
    - <<: *deploy_base
      on:
        <<: *repo_filter
        tags: false

jobs:
  include:
    # Make and deploy charts with reference python
    - <<: *make_charts
      <<: *deploy
      <<: *python_reference_environment
      stage: deploy
