[configurationNetwork]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# fraction of LoRa device on edge
gamma = [0.0, 0.33, 0.66, 1.0]
# fraction of device on smartphone
beta = [0.0, 0.33, 0.66, 1.0]
dee = [0.1, 1.0, 10.0]
dcc = [5, 25, 100]
dec = [10, 50, 300, 1000]
dscnd = [50, 150, 500]
dlocalhost = 0.015

[brokerHostConfig]
type = ["CLOUD", "EDGE"]
dataRate = 1e9

[[hostsConfig]]
    type = "CLOUD"
    id = "c000"
[[hostsConfig]]
    type = "EDGE"
    dataRate = 10
