[configurationNetwork]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# probability of LoRa device on edge
gamma = [1.0]
# probability of device on smartphone
beta = [0.004, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]
dee = [1.0]
dcc = [25]
dec = [50]
dscnd = [150]
dlocalhost = 0.015

[brokerHostConfig]
type = ["CLOUD"]
dataRate = 1e9

[[hostsConfig]]
    type = "CLOUD"
    id = "c000"
[[hostsConfig]]
    type = "EDGE"
    dataRate = 10
