[configurationNetwork]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# probability of LoRa device on edge
gamma = [1.0]
# probability of device on smartphone
beta = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9 1.0]
dee = [1.0]
dcc = [25]
dec = [50]
dscnd = [150]
dlocalhost = 0.015

[brokerHostConfig]
type = ["CLOUD"]
dataRate = 1e9

[[hostsConfig]]
    type = "CLOUD"
    id = "c000"
[[hostsConfig]]
    type = "EDGE"
    dataRate = 10
